### ISSUE TITLE
TODO - Create CAPIv2 Scripts

### ISSUE THREAD

**Issue by derrickmehaffy** [canonn-science/CAPIv2-Strapi#164]
**Scripts to Create**

- [ ] EDSM Systems Update
- [ ] EDSM Body Update
- [ ] Kill Reports
- [ ] GR/GS Reports (GR not currently possible, GS needs EDMC-Canonn Changes)
- [ ] voteCount verified to mark sites as verified
- [ ] Cleanup Scripts to remove old data after x months

**Scripts Complete**

- [x] Material Report Cleanup after 1 month
- [x] Basic Report Validation (Create, Update, Duplicate, Error)

**Comment by derrickmehaffy** [comment]
closing as these scripts are in the process of being moved to their own repo
