### ISSUE TITLE
Update to Strapi 14.2 To-Do list

### ISSUE THREAD

**Issue by derrickmehaffy** [canonn-science/CAPIv2-Strapi#93]
To Do List:

- [x] Core update
- [x] Update seed files
- [x] Update tests
- [x] Update Swagger Docs
- [x] Minor README updates
- [x] Testing of new plural routes
- [x] Update public model files for Athena/Athens

**Comment by derrickmehaffy** [comment]
Testing of plural routes was only done on a few. TravisCI tests passed for reports, further testing will need to be done on other models.

**Comment by derrickmehaffy** [comment]
Public models, only the report models currently have x-data thus only those were updated.

**Comment by derrickmehaffy** [comment]
Marking as closed pending TravisCI tests and related PR
